name: LifeTracker
options:
  bundleIdPrefix: com.lifetracker
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  LifeTracker:
    type: application
    platform: iOS
    sources:
      - path: LifeTracker
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lifetracker.app
        INFOPLIST_KEY_CFBundleDisplayName: LifeTracker
        INFOPLIST_KEY_NSCameraUsageDescription: "LifeTracker needs camera access to scan documents and barcodes"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "LifeTracker needs photo library access to save and import images"
        INFOPLIST_KEY_NSHealthShareUsageDescription: "LifeTracker reads health data to display your fitness metrics"
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "LifeTracker writes workout and measurement data to Health"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
        CODE_SIGN_ENTITLEMENTS: LifeTracker/LifeTracker.entitlements
    dependencies:
      - target: LifeTrackerWidgets

  LifeTrackerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LifeTrackerTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lifetracker.tests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/LifeTracker.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/LifeTracker"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: LifeTracker

  LifeTrackerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LifeTrackerUITests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lifetracker.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: LifeTracker
    dependencies:
      - target: LifeTracker

  LifeTrackerWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: LifeTrackerWidgets
        excludes:
          - "**/.DS_Store"
    info:
      path: LifeTrackerWidgets/Info.plist
      properties:
        CFBundleDisplayName: LifeTracker Widgets
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lifetracker.app.widgets
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        CODE_SIGN_ENTITLEMENTS: LifeTrackerWidgets/LifeTrackerWidgets.entitlements
        SKIP_INSTALL: YES

schemes:
  LifeTracker:
    build:
      targets:
        LifeTracker: all
        LifeTrackerTests: [test]
        LifeTrackerUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - LifeTrackerTests
        - LifeTrackerUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
